/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.inf514.sistemacooperativa.vista;

/**
 *
 * @author jfria
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    /**
     * Creates new form ResgirterMainScreen
     */
    public FrmPrincipal() {
        initComponents();
        
        mostrarPanel(new PnlMiembros());
    }
    
    private void mostrarPanel(javax.swing.JPanel panelNuevo) {
        //ajusta el panel entrante a la dimensiones del contenedor
       
        panelNuevo.setSize(pnlContenedor.getWidth(), pnlContenedor.getHeight());
        panelNuevo.setLocation(0, 0);
       //limpia el contenedor y añade la nueva vista
        pnlContenedor.removeAll();
        pnlContenedor.add(panelNuevo, java.awt.BorderLayout.CENTER);
        //refresca la interfaz grafica para que los cambios sean visible 
        pnlContenedor.revalidate();
        pnlContenedor.repaint();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnbackground = new javax.swing.JPanel();
        pnlHeaderPanel = new javax.swing.JPanel();
        pnlLogo = new javax.swing.JPanel();
        txtSistemadeCooperativa = new javax.swing.JLabel();
        txtLogo = new javax.swing.JLabel();
        pnlContenedor = new javax.swing.JPanel();
        pnlSidePanel = new javax.swing.JPanel();
        panelInicioBoton = new javax.swing.JPanel();
        txtInicio = new javax.swing.JLabel();
        panelMienbroBoton = new javax.swing.JPanel();
        txtMiembroBoton = new javax.swing.JLabel();
        panelPestamoBoton = new javax.swing.JPanel();
        txtPrestamosBoton = new javax.swing.JLabel();
        panelAhorroBoton = new javax.swing.JPanel();
        lblAhoros = new javax.swing.JLabel();
        pnlBottonPanel = new javax.swing.JPanel();
        lblVersion = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnbackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeaderPanel.setBackground(new java.awt.Color(24, 75, 95));

        pnlLogo.setBackground(new java.awt.Color(221, 238, 249));
        pnlLogo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51)));

        txtSistemadeCooperativa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtSistemadeCooperativa.setForeground(new java.awt.Color(24, 75, 95));
        txtSistemadeCooperativa.setText("SISTEMA DE COOPERATIVA");

        txtLogo.setIcon(new javax.swing.ImageIcon("D:\\user\\Julio\\UASD\\ProgramacionII\\trabajo-en-equipo64.png")); // NOI18N

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(txtSistemadeCooperativa)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGroup(pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLogo)
                    .addGroup(pnlLogoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtSistemadeCooperativa)))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout pnlHeaderPanelLayout = new javax.swing.GroupLayout(pnlHeaderPanel);
        pnlHeaderPanel.setLayout(pnlHeaderPanelLayout);
        pnlHeaderPanelLayout.setHorizontalGroup(
            pnlHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderPanelLayout.createSequentialGroup()
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 604, Short.MAX_VALUE))
        );
        pnlHeaderPanelLayout.setVerticalGroup(
            pnlHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnbackground.add(pnlHeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1210, 110));

        pnlContenedor.setBackground(new java.awt.Color(244, 239, 230));

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        pnbackground.add(pnlContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 1040, 530));

        pnlSidePanel.setBackground(new java.awt.Color(221, 238, 249));

        panelInicioBoton.setBackground(new java.awt.Color(221, 238, 249));
        panelInicioBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelInicioBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelInicioBotonMouseClicked(evt);
            }
        });

        txtInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtInicio.setForeground(new java.awt.Color(0, 0, 0));
        txtInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtInicio.setText("Inicio");

        javax.swing.GroupLayout panelInicioBotonLayout = new javax.swing.GroupLayout(panelInicioBoton);
        panelInicioBoton.setLayout(panelInicioBotonLayout);
        panelInicioBotonLayout.setHorizontalGroup(
            panelInicioBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioBotonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        panelInicioBotonLayout.setVerticalGroup(
            panelInicioBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioBotonLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        panelMienbroBoton.setBackground(new java.awt.Color(221, 238, 249));
        panelMienbroBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMienbroBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMienbroBotonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMienbroBotonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelMienbroBotonMouseReleased(evt);
            }
        });

        txtMiembroBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMiembroBoton.setForeground(new java.awt.Color(0, 0, 0));
        txtMiembroBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMiembroBoton.setText("Miembros");
        txtMiembroBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelMienbroBotonLayout = new javax.swing.GroupLayout(panelMienbroBoton);
        panelMienbroBoton.setLayout(panelMienbroBotonLayout);
        panelMienbroBotonLayout.setHorizontalGroup(
            panelMienbroBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMienbroBotonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtMiembroBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelMienbroBotonLayout.setVerticalGroup(
            panelMienbroBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMienbroBotonLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(txtMiembroBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        panelPestamoBoton.setBackground(new java.awt.Color(221, 238, 249));
        panelPestamoBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelPestamoBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPestamoBotonMouseClicked(evt);
            }
        });

        txtPrestamosBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPrestamosBoton.setForeground(new java.awt.Color(0, 0, 0));
        txtPrestamosBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPrestamosBoton.setText("Prestamos");
        txtPrestamosBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelPestamoBotonLayout = new javax.swing.GroupLayout(panelPestamoBoton);
        panelPestamoBoton.setLayout(panelPestamoBotonLayout);
        panelPestamoBotonLayout.setHorizontalGroup(
            panelPestamoBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPestamoBotonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtPrestamosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPestamoBotonLayout.setVerticalGroup(
            panelPestamoBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPestamoBotonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPrestamosBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelAhorroBoton.setBackground(new java.awt.Color(221, 238, 249));
        panelAhorroBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblAhoros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAhoros.setForeground(new java.awt.Color(0, 0, 0));
        lblAhoros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAhoros.setText("Ahorros");

        javax.swing.GroupLayout panelAhorroBotonLayout = new javax.swing.GroupLayout(panelAhorroBoton);
        panelAhorroBoton.setLayout(panelAhorroBotonLayout);
        panelAhorroBotonLayout.setHorizontalGroup(
            panelAhorroBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAhorroBotonLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblAhoros, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAhorroBotonLayout.setVerticalGroup(
            panelAhorroBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAhorroBotonLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblAhoros, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlSidePanelLayout = new javax.swing.GroupLayout(pnlSidePanel);
        pnlSidePanel.setLayout(pnlSidePanelLayout);
        pnlSidePanelLayout.setHorizontalGroup(
            pnlSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAhorroBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPestamoBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMienbroBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInicioBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlSidePanelLayout.setVerticalGroup(
            pnlSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidePanelLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(panelInicioBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(panelMienbroBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(panelPestamoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(panelAhorroBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        pnbackground.add(pnlSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 530));

        pnlBottonPanel.setBackground(new java.awt.Color(221, 238, 249));
        pnlBottonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51)));

        lblVersion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblVersion.setForeground(new java.awt.Color(0, 0, 0));
        lblVersion.setText("Version:");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        lblFecha.setText("Fecha:");

        javax.swing.GroupLayout pnlBottonPanelLayout = new javax.swing.GroupLayout(pnlBottonPanel);
        pnlBottonPanel.setLayout(pnlBottonPanelLayout);
        pnlBottonPanelLayout.setHorizontalGroup(
            pnlBottonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottonPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 565, Short.MAX_VALUE)
                .addComponent(lblVersion)
                .addGap(132, 132, 132))
        );
        pnlBottonPanelLayout.setVerticalGroup(
            pnlBottonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBottonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVersion, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(lblFecha, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        pnbackground.add(pnlBottonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnbackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelMienbroBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMienbroBotonMousePressed

        panelMienbroBoton.setBackground(new java.awt.Color(190,221,239));        // TODO add your handling code here:
    }//GEN-LAST:event_panelMienbroBotonMousePressed

    private void panelMienbroBotonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMienbroBotonMouseReleased
        // TODO add your handling code here:
        panelMienbroBoton.setBackground(new java.awt.Color(221, 238, 249));
    }//GEN-LAST:event_panelMienbroBotonMouseReleased

    private void panelInicioBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelInicioBotonMouseClicked
        // TODO add your handling code here:
        mostrarPanel(new PnlInicio());
    }//GEN-LAST:event_panelInicioBotonMouseClicked

    private void panelMienbroBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMienbroBotonMouseClicked
        // TODO add your handling code here:
        mostrarPanel(new PnlMiembros());
    }//GEN-LAST:event_panelMienbroBotonMouseClicked

    private void panelPestamoBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPestamoBotonMouseClicked
        // TODO add your handling code here:
        mostrarPanel(new PnlPrestamos());
    }//GEN-LAST:event_panelPestamoBotonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAhoros;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JPanel panelAhorroBoton;
    private javax.swing.JPanel panelInicioBoton;
    private javax.swing.JPanel panelMienbroBoton;
    private javax.swing.JPanel panelPestamoBoton;
    private javax.swing.JPanel pnbackground;
    private javax.swing.JPanel pnlBottonPanel;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlHeaderPanel;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlSidePanel;
    private javax.swing.JLabel txtInicio;
    private javax.swing.JLabel txtLogo;
    private javax.swing.JLabel txtMiembroBoton;
    private javax.swing.JLabel txtPrestamosBoton;
    private javax.swing.JLabel txtSistemadeCooperativa;
    // End of variables declaration//GEN-END:variables
}
