/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.inf514.sistemacooperativa.vista;

/**
 *
 * @author jfria
 */
public class MainLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainLogin.class.getName());

    /**
     * Creates new form MainLogin
     */
    public MainLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundMainLogin = new javax.swing.JPanel();
        pnlBackgroudLogo = new javax.swing.JPanel();
        lblIconCooperativa = new javax.swing.JLabel();
        lblSistemaDeCooperativa = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlBackgroundLoginForm = new javax.swing.JPanel();
        lblInicioDeSesion = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblContrasenia = new javax.swing.JLabel();
        pnBottonIngresar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pwdContrasenia = new javax.swing.JPasswordField();
        pnlBackgroundRegistro = new javax.swing.JPanel();
        lblRegistroNuevoUsuario = new javax.swing.JLabel();
        lblNombreCompleto = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        tfNombreCompleto = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField3 = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreoElectronico = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDireccion = new javax.swing.JTextArea();
        pnlRegistarBotton = new javax.swing.JPanel();
        txtRegistar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundMainLogin.setBackground(new java.awt.Color(24, 75, 95));
        backgroundMainLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBackgroudLogo.setBackground(new java.awt.Color(221, 238, 249));

        lblIconCooperativa.setIcon(new javax.swing.ImageIcon("D:\\user\\Julio\\UASD\\ProgramacionII\\trabajo-en-equipo256.png")); // NOI18N

        javax.swing.GroupLayout pnlBackgroudLogoLayout = new javax.swing.GroupLayout(pnlBackgroudLogo);
        pnlBackgroudLogo.setLayout(pnlBackgroudLogoLayout);
        pnlBackgroudLogoLayout.setHorizontalGroup(
            pnlBackgroudLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroudLogoLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblIconCooperativa)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        pnlBackgroudLogoLayout.setVerticalGroup(
            pnlBackgroudLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroudLogoLayout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(lblIconCooperativa)
                .addGap(162, 162, 162))
        );

        backgroundMainLogin.add(pnlBackgroudLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 600));

        lblSistemaDeCooperativa.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblSistemaDeCooperativa.setForeground(new java.awt.Color(0, 0, 0));
        lblSistemaDeCooperativa.setText("Sistema de cooperativa");
        backgroundMainLogin.add(lblSistemaDeCooperativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        pnlBackgroundLoginForm.setBackground(new java.awt.Color(244, 239, 230));

        lblInicioDeSesion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblInicioDeSesion.setForeground(new java.awt.Color(0, 0, 0));
        lblInicioDeSesion.setText("Inicio de Sesion");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Cedula");

        txtNombre.setText("Digite su Cedula sin guiones");
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));

        lblContrasenia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContrasenia.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasenia.setText("Contraseña:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ingresar");

        javax.swing.GroupLayout pnBottonIngresarLayout = new javax.swing.GroupLayout(pnBottonIngresar);
        pnBottonIngresar.setLayout(pnBottonIngresarLayout);
        pnBottonIngresarLayout.setHorizontalGroup(
            pnBottonIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBottonIngresarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pnBottonIngresarLayout.setVerticalGroup(
            pnBottonIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBottonIngresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Registrar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        pwdContrasenia.setText("jPasswordField2");

        javax.swing.GroupLayout pnlBackgroundLoginFormLayout = new javax.swing.GroupLayout(pnlBackgroundLoginForm);
        pnlBackgroundLoginForm.setLayout(pnlBackgroundLoginFormLayout);
        pnlBackgroundLoginFormLayout.setHorizontalGroup(
            pnlBackgroundLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLoginFormLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(pnlBackgroundLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblInicioDeSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContrasenia)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addGroup(pnlBackgroundLoginFormLayout.createSequentialGroup()
                        .addComponent(pnBottonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pwdContrasenia))
                .addGap(0, 120, Short.MAX_VALUE))
        );
        pnlBackgroundLoginFormLayout.setVerticalGroup(
            pnlBackgroundLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLoginFormLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblInicioDeSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(pnlBackgroundLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBackgroundLoginFormLayout.createSequentialGroup()
                        .addComponent(lblContrasenia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pwdContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(pnBottonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Login", pnlBackgroundLoginForm);

        pnlBackgroundRegistro.setBackground(new java.awt.Color(244, 239, 230));

        lblRegistroNuevoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblRegistroNuevoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblRegistroNuevoUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblRegistroNuevoUsuario.setText("Registro Nuevo usuario");

        lblNombreCompleto.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreCompleto.setText("Nombre Completo");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Telefono:");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Correo Electronico:");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Contrasenia:");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Fecha de nacimiento");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Direccion:");

        lblCedula.setForeground(new java.awt.Color(0, 0, 0));
        lblCedula.setText("Cedula");

        txtApellido.setText("digite su cedula sin guiones");
        txtApellido.addActionListener(this::txtApellidoActionPerformed);

        tfNombreCompleto.setText("Nombre Completo");

        jPasswordField1.setText("jPasswordField1");

        jTextField3.setText("fecha de nacimiento");
        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        txtTelefono.setText("Telefono");
        txtTelefono.addActionListener(this::txtTelefonoActionPerformed);

        txtCorreoElectronico.setText("Corro Electronico");

        txaDireccion.setColumns(20);
        txaDireccion.setRows(5);
        jScrollPane1.setViewportView(txaDireccion);

        txtRegistar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRegistar.setText("REGISTAR");

        javax.swing.GroupLayout pnlRegistarBottonLayout = new javax.swing.GroupLayout(pnlRegistarBotton);
        pnlRegistarBotton.setLayout(pnlRegistarBottonLayout);
        pnlRegistarBottonLayout.setHorizontalGroup(
            pnlRegistarBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistarBottonLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(txtRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlRegistarBottonLayout.setVerticalGroup(
            pnlRegistarBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistarBottonLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtRegistar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBackgroundRegistroLayout = new javax.swing.GroupLayout(pnlBackgroundRegistro);
        pnlBackgroundRegistro.setLayout(pnlBackgroundRegistroLayout);
        pnlBackgroundRegistroLayout.setHorizontalGroup(
            pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundRegistroLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(lblRegistroNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlBackgroundRegistroLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundRegistroLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCedula)
                            .addComponent(lblNombreCompleto)
                            .addComponent(txtApellido)
                            .addComponent(tfNombreCompleto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13)
                            .addComponent(txtCorreoElectronico, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jLabel12)
                            .addComponent(jPasswordField1))
                        .addGap(82, 82, 82))
                    .addGroup(pnlBackgroundRegistroLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlRegistarBotton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(pnlBackgroundRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackgroundRegistroLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addContainerGap(400, Short.MAX_VALUE))
                            .addGroup(pnlBackgroundRegistroLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        pnlBackgroundRegistroLayout.setVerticalGroup(
            pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistroNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(lblNombreCompleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundRegistroLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackgroundRegistroLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBackgroundRegistroLayout.createSequentialGroup()
                                .addComponent(lblCedula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundRegistroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundRegistroLayout.createSequentialGroup()
                        .addComponent(pnlRegistarBotton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registro", pnlBackgroundRegistro);

        backgroundMainLogin.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 630, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundMainLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundMainLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

 
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundMainLogin;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblIconCooperativa;
    private javax.swing.JLabel lblInicioDeSesion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreCompleto;
    private javax.swing.JLabel lblRegistroNuevoUsuario;
    private javax.swing.JLabel lblSistemaDeCooperativa;
    private javax.swing.JPanel pnBottonIngresar;
    private javax.swing.JPanel pnlBackgroudLogo;
    private javax.swing.JPanel pnlBackgroundLoginForm;
    private javax.swing.JPanel pnlBackgroundRegistro;
    private javax.swing.JPanel pnlRegistarBotton;
    private javax.swing.JPasswordField pwdContrasenia;
    private javax.swing.JTextField tfNombreCompleto;
    private javax.swing.JTextArea txaDireccion;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JLabel txtRegistar;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
