/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.inf514.sistemacooperativa.vista;

/**
 *
 * @author jfria
 */
public class MiembroScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MiembroScreen.class.getName());

    /**
     * Creates new form ResgirterMainScreen
     */
    public MiembroScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnbackground = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        pnlLogo = new javax.swing.JPanel();
        txtSistemadeCooperativa = new javax.swing.JLabel();
        txtLogo = new javax.swing.JLabel();
        pnlConten = new javax.swing.JPanel();
        txtGestionDeMiembros = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMiembros = new javax.swing.JTable();
        panelNuevoMiembro = new javax.swing.JPanel();
        txtNuevoMiembro = new javax.swing.JLabel();
        txtPlusIcon = new javax.swing.JLabel();
        panelExportarListado = new javax.swing.JPanel();
        txtPageicon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelModificar = new javax.swing.JPanel();
        txtModificar = new javax.swing.JLabel();
        panelEliminar = new javax.swing.JPanel();
        txtEliminar = new javax.swing.JLabel();
        txtBuscarPorCedulaOID = new javax.swing.JLabel();
        tfBusquedaPorCedulaOID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        txtTipodeCuenta = new javax.swing.JLabel();
        cbTipoDeCuenta = new javax.swing.JComboBox<>();
        pnlSidePanel = new javax.swing.JPanel();
        panelInicioBoton = new javax.swing.JPanel();
        txtInicio = new javax.swing.JLabel();
        panelMienbroBotton = new javax.swing.JPanel();
        txtMiembroBoton = new javax.swing.JLabel();
        panelPestamoBoton = new javax.swing.JPanel();
        txtPrestamosBoton = new javax.swing.JLabel();
        panelReporteBoton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlBotton = new javax.swing.JPanel();
        txtVersion = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnbackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(24, 75, 95));

        pnlLogo.setBackground(new java.awt.Color(221, 238, 249));
        pnlLogo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51)));

        txtSistemadeCooperativa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtSistemadeCooperativa.setForeground(new java.awt.Color(24, 75, 95));
        txtSistemadeCooperativa.setText("SISTEMA DE COOPERATIVA");

        txtLogo.setIcon(new javax.swing.ImageIcon("D:\\user\\Julio\\UASD\\ProgramacionII\\trabajo-en-equipo64.png")); // NOI18N

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSistemadeCooperativa)
                .addContainerGap(483, Short.MAX_VALUE))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGroup(pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLogoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(txtSistemadeCooperativa))
                    .addGroup(pnlLogoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(txtLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 310, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnbackground.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1210, 110));

        pnlConten.setBackground(new java.awt.Color(244, 239, 230));

        txtGestionDeMiembros.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtGestionDeMiembros.setForeground(new java.awt.Color(24, 75, 95));
        txtGestionDeMiembros.setText("GESTION DE MIEMBROS");

        jScrollPane1.setBackground(new java.awt.Color(244, 239, 230));

        tableMiembros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableMiembros);

        txtNuevoMiembro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNuevoMiembro.setText(" Nuevo Miembro");

        txtPlusIcon.setText("➕");

        javax.swing.GroupLayout panelNuevoMiembroLayout = new javax.swing.GroupLayout(panelNuevoMiembro);
        panelNuevoMiembro.setLayout(panelNuevoMiembroLayout);
        panelNuevoMiembroLayout.setHorizontalGroup(
            panelNuevoMiembroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevoMiembroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPlusIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNuevoMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panelNuevoMiembroLayout.setVerticalGroup(
            panelNuevoMiembroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevoMiembroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNuevoMiembroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevoMiembro, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(txtPlusIcon))
                .addContainerGap())
        );

        txtPageicon.setText("📄");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Exportar Listado");

        javax.swing.GroupLayout panelExportarListadoLayout = new javax.swing.GroupLayout(panelExportarListado);
        panelExportarListado.setLayout(panelExportarListadoLayout);
        panelExportarListadoLayout.setHorizontalGroup(
            panelExportarListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExportarListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPageicon, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelExportarListadoLayout.setVerticalGroup(
            panelExportarListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExportarListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelExportarListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPageicon, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        txtModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtModificar.setText("️  Modificar");

        javax.swing.GroupLayout panelModificarLayout = new javax.swing.GroupLayout(panelModificar);
        panelModificar.setLayout(panelModificarLayout);
        panelModificarLayout.setHorizontalGroup(
            panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtModificar)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelModificarLayout.setVerticalGroup(
            panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtEliminar.setText("Eliminar");

        javax.swing.GroupLayout panelEliminarLayout = new javax.swing.GroupLayout(panelEliminar);
        panelEliminar.setLayout(panelEliminarLayout);
        panelEliminarLayout.setHorizontalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(txtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        panelEliminarLayout.setVerticalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtBuscarPorCedulaOID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtBuscarPorCedulaOID.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscarPorCedulaOID.setText("Buscar por cedula o ID");

        tfBusquedaPorCedulaOID.setText("🔍 Busqueda por cedula o ID");
        tfBusquedaPorCedulaOID.addActionListener(this::tfBusquedaPorCedulaOIDActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Estado");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado", "Activo", "Pendiente", "Inactivo" }));

        txtTipodeCuenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTipodeCuenta.setForeground(new java.awt.Color(0, 0, 0));
        txtTipodeCuenta.setText("Tipo de Cuenta");

        cbTipoDeCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Cuenta", "Ahorro", "Corriente", "Credito" }));

        javax.swing.GroupLayout pnlContenLayout = new javax.swing.GroupLayout(pnlConten);
        pnlConten.setLayout(pnlContenLayout);
        pnlContenLayout.setHorizontalGroup(
            pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenLayout.createSequentialGroup()
                        .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscarPorCedulaOID)
                            .addComponent(tfBusquedaPorCedulaOID, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGestionDeMiembros))
                        .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContenLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(pnlContenLayout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(panelNuevoMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panelExportarListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipodeCuenta)
                            .addComponent(cbTipoDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(392, 392, 392)
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContenLayout.setVerticalGroup(
            pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(panelModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(panelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlContenLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelNuevoMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGestionDeMiembros)
                    .addComponent(panelExportarListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipodeCuenta)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscarPorCedulaOID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBusquedaPorCedulaOID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pnbackground.add(pnlConten, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 1040, 530));

        pnlSidePanel.setBackground(new java.awt.Color(221, 238, 249));
        pnlSidePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        txtInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtInicio.setText("Inicio");

        javax.swing.GroupLayout panelInicioBotonLayout = new javax.swing.GroupLayout(panelInicioBoton);
        panelInicioBoton.setLayout(panelInicioBotonLayout);
        panelInicioBotonLayout.setHorizontalGroup(
            panelInicioBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioBotonLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInicioBotonLayout.setVerticalGroup(
            panelInicioBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioBotonLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        txtMiembroBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMiembroBoton.setText("Miembro");

        javax.swing.GroupLayout panelMienbroBottonLayout = new javax.swing.GroupLayout(panelMienbroBotton);
        panelMienbroBotton.setLayout(panelMienbroBottonLayout);
        panelMienbroBottonLayout.setHorizontalGroup(
            panelMienbroBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMienbroBottonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtMiembroBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMienbroBottonLayout.setVerticalGroup(
            panelMienbroBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMienbroBottonLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(txtMiembroBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        txtPrestamosBoton.setText("Prestamos");

        javax.swing.GroupLayout panelPestamoBotonLayout = new javax.swing.GroupLayout(panelPestamoBoton);
        panelPestamoBoton.setLayout(panelPestamoBotonLayout);
        panelPestamoBotonLayout.setHorizontalGroup(
            panelPestamoBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPestamoBotonLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtPrestamosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelPestamoBotonLayout.setVerticalGroup(
            panelPestamoBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPestamoBotonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPrestamosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Reportes");

        javax.swing.GroupLayout panelReporteBotonLayout = new javax.swing.GroupLayout(panelReporteBoton);
        panelReporteBoton.setLayout(panelReporteBotonLayout);
        panelReporteBotonLayout.setHorizontalGroup(
            panelReporteBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteBotonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelReporteBotonLayout.setVerticalGroup(
            panelReporteBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteBotonLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlSidePanelLayout = new javax.swing.GroupLayout(pnlSidePanel);
        pnlSidePanel.setLayout(pnlSidePanelLayout);
        pnlSidePanelLayout.setHorizontalGroup(
            pnlSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelReporteBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPestamoBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMienbroBotton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInicioBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlSidePanelLayout.setVerticalGroup(
            pnlSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidePanelLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(panelInicioBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(panelMienbroBotton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(panelPestamoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(panelReporteBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        pnbackground.add(pnlSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 530));

        pnlBotton.setBackground(new java.awt.Color(221, 238, 249));
        pnlBotton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51)));

        txtVersion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtVersion.setForeground(new java.awt.Color(0, 0, 0));
        txtVersion.setText("Version:");

        txtFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(0, 0, 0));
        txtFecha.setText("Fecha:");

        javax.swing.GroupLayout pnlBottonLayout = new javax.swing.GroupLayout(pnlBotton);
        pnlBotton.setLayout(pnlBottonLayout);
        pnlBottonLayout.setHorizontalGroup(
            pnlBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottonLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 564, Short.MAX_VALUE)
                .addComponent(txtVersion)
                .addGap(133, 133, 133))
        );
        pnlBottonLayout.setVerticalGroup(
            pnlBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVersion, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtFecha))
                .addContainerGap())
        );

        pnbackground.add(pnlBotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnbackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfBusquedaPorCedulaOIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBusquedaPorCedulaOIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBusquedaPorCedulaOIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbTipoDeCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelEliminar;
    private javax.swing.JPanel panelExportarListado;
    private javax.swing.JPanel panelInicioBoton;
    private javax.swing.JPanel panelMienbroBotton;
    private javax.swing.JPanel panelModificar;
    private javax.swing.JPanel panelNuevoMiembro;
    private javax.swing.JPanel panelPestamoBoton;
    private javax.swing.JPanel panelReporteBoton;
    private javax.swing.JPanel pnbackground;
    private javax.swing.JPanel pnlBotton;
    private javax.swing.JPanel pnlConten;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlSidePanel;
    private javax.swing.JTable tableMiembros;
    private javax.swing.JTextField tfBusquedaPorCedulaOID;
    private javax.swing.JLabel txtBuscarPorCedulaOID;
    private javax.swing.JLabel txtEliminar;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtGestionDeMiembros;
    private javax.swing.JLabel txtInicio;
    private javax.swing.JLabel txtLogo;
    private javax.swing.JLabel txtMiembroBoton;
    private javax.swing.JLabel txtModificar;
    private javax.swing.JLabel txtNuevoMiembro;
    private javax.swing.JLabel txtPageicon;
    private javax.swing.JLabel txtPlusIcon;
    private javax.swing.JLabel txtPrestamosBoton;
    private javax.swing.JLabel txtSistemadeCooperativa;
    private javax.swing.JLabel txtTipodeCuenta;
    private javax.swing.JLabel txtVersion;
    // End of variables declaration//GEN-END:variables
}
