/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.inf514.sistemacooperativa.vista;

/**
 *
 * @author jfria
 */
public class PnlMiembros extends javax.swing.JPanel {

    /**
     * Creates new form PnlMiembros
     */
    public PnlMiembros() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGestionDeMiembros = new javax.swing.JLabel();
        panelNuevoMiembro = new javax.swing.JPanel();
        txtNuevoMiembro = new javax.swing.JLabel();
        txtPlusIcon = new javax.swing.JLabel();
        panelExportarListado = new javax.swing.JPanel();
        txtPageicon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelModificar = new javax.swing.JPanel();
        txtModificar = new javax.swing.JLabel();
        panelEliminar = new javax.swing.JPanel();
        txtEliminar = new javax.swing.JLabel();
        lblBuscarPorCedulaOID = new javax.swing.JLabel();
        txtBuscarporCedulaOID = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        lblTipodeCuenta = new javax.swing.JLabel();
        cbTipoDeCuenta = new javax.swing.JComboBox<>();
        jScrollPaneTablaMiembros = new javax.swing.JScrollPane();
        tableMiembros = new javax.swing.JTable();

        txtGestionDeMiembros.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtGestionDeMiembros.setForeground(new java.awt.Color(24, 75, 95));
        txtGestionDeMiembros.setText("GESTION DE MIEMBROS");

        txtNuevoMiembro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNuevoMiembro.setText(" Nuevo Miembro");

        txtPlusIcon.setText("➕");

        javax.swing.GroupLayout panelNuevoMiembroLayout = new javax.swing.GroupLayout(panelNuevoMiembro);
        panelNuevoMiembro.setLayout(panelNuevoMiembroLayout);
        panelNuevoMiembroLayout.setHorizontalGroup(
            panelNuevoMiembroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevoMiembroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPlusIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNuevoMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panelNuevoMiembroLayout.setVerticalGroup(
            panelNuevoMiembroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevoMiembroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNuevoMiembroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevoMiembro, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(txtPlusIcon))
                .addContainerGap())
        );

        txtPageicon.setText("📄");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Exportar Listado");

        javax.swing.GroupLayout panelExportarListadoLayout = new javax.swing.GroupLayout(panelExportarListado);
        panelExportarListado.setLayout(panelExportarListadoLayout);
        panelExportarListadoLayout.setHorizontalGroup(
            panelExportarListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExportarListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPageicon, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelExportarListadoLayout.setVerticalGroup(
            panelExportarListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExportarListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelExportarListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPageicon, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        txtModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtModificar.setText("️  Modificar");

        javax.swing.GroupLayout panelModificarLayout = new javax.swing.GroupLayout(panelModificar);
        panelModificar.setLayout(panelModificarLayout);
        panelModificarLayout.setHorizontalGroup(
            panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(txtModificar)
                .addGap(20, 20, 20))
        );
        panelModificarLayout.setVerticalGroup(
            panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtEliminar.setText("Eliminar");

        javax.swing.GroupLayout panelEliminarLayout = new javax.swing.GroupLayout(panelEliminar);
        panelEliminar.setLayout(panelEliminarLayout);
        panelEliminarLayout.setHorizontalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(txtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        panelEliminarLayout.setVerticalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblBuscarPorCedulaOID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBuscarPorCedulaOID.setForeground(new java.awt.Color(0, 0, 0));
        lblBuscarPorCedulaOID.setText("Buscar por cedula o ID");

        txtBuscarporCedulaOID.setText("🔍 Busqueda por cedula o ID");
        txtBuscarporCedulaOID.addActionListener(this::txtBuscarporCedulaOIDActionPerformed);

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(0, 0, 0));
        lblEstado.setText("Estado");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado", "Activo", "Pendiente", "Inactivo" }));

        lblTipodeCuenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTipodeCuenta.setForeground(new java.awt.Color(0, 0, 0));
        lblTipodeCuenta.setText("Tipo de Cuenta");

        cbTipoDeCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Cuenta", "Ahorro", "Corriente", "Credito" }));

        jScrollPaneTablaMiembros.setBackground(new java.awt.Color(244, 239, 230));

        tableMiembros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneTablaMiembros.setViewportView(tableMiembros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtGestionDeMiembros)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEstado)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(panelNuevoMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panelExportarListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPaneTablaMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBuscarPorCedulaOID)
                                    .addComponent(txtBuscarporCedulaOID, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipodeCuenta)
                                    .addComponent(cbTipoDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelNuevoMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGestionDeMiembros)
                    .addComponent(panelExportarListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipodeCuenta)
                    .addComponent(lblEstado)
                    .addComponent(lblBuscarPorCedulaOID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarporCedulaOID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTablaMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(panelModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void txtBuscarporCedulaOIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarporCedulaOIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarporCedulaOIDActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbTipoDeCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPaneTablaMiembros;
    private javax.swing.JLabel lblBuscarPorCedulaOID;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblTipodeCuenta;
    private javax.swing.JPanel panelEliminar;
    private javax.swing.JPanel panelExportarListado;
    private javax.swing.JPanel panelModificar;
    private javax.swing.JPanel panelNuevoMiembro;
    private javax.swing.JTable tableMiembros;
    private javax.swing.JTextField txtBuscarporCedulaOID;
    private javax.swing.JLabel txtEliminar;
    private javax.swing.JLabel txtGestionDeMiembros;
    private javax.swing.JLabel txtModificar;
    private javax.swing.JLabel txtNuevoMiembro;
    private javax.swing.JLabel txtPageicon;
    private javax.swing.JLabel txtPlusIcon;
    // End of variables declaration//GEN-END:variables
}
